# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-33709-jiu-730QCJ-730QCR/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog
    /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_bfm_v2_0/adcdcea3/hdl
    /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_processing_system7_0
  } {
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_pll.sv
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_pwm.sv
    }
      rt::read_verilog -include {
    /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog
    /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_bfm_v2_0/adcdcea3/hdl
    /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_processing_system7_0
  } {
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_and.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_or.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/synth/system_axi_protocol_converter_0_0.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_atc.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/ad955ff5/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_processing_system7_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_processing_system7_0/synth/system_processing_system7_0.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/xlconstant_v1_1/36911fd5/xlconstant.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xlconstant_0/sim/system_xlconstant_0.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/hdl/system.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/hdl/system_wrapper.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/axi_master.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/axi_slave.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/axi_wr_fifo.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_ams.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_asg_ch.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_asg.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_dfilt1.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_hk.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_pid_block.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_pid.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_ps.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_scope.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/red_pitaya_top.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/aDACdecoder.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/LP_filter.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/LP_filter2.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/LP_filter3.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/mult_dsp_14.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/sq_mult.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/muxer3.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/muxer4.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/muxer5.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/muxer_reg3.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/muxer_reg4.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/muxer_reg5.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/gen_mod2.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/gen_ramp.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/gen_ramp_relock.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/lock_ctrl.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/lock_pid_block.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/slope9.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/sat14.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/satprotect.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/debounce.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/trigger_input.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/jump_control.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/sum_2N2.v
      /home/jiu/ma/jiu3/lock_in_48/fpga/rtl/lock/pipe_mult.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_2 {
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/7b054ed9/hdl/blk_mem_gen_v8_2_vhsyn_rfs.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/7b054ed9/hdl/blk_mem_gen_v8_2.vhd
    }
      rt::read_vhdl -lib fifo_generator_v12_0 {
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0_vhsyn_rfs.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0 /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/lib_cdc_v1_0/ea79928f/hdl/src/vhdl/cdc_sync.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0 {
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/upcnt_n.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/sequence.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/lpf.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/proc_sys_reset.vhd
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/synth/system_proc_sys_reset_0.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_conv_funs_pkg.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_proc_common_pkg.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_ipif_pkg.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_family_support.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_family.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_soft_reset.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/proc_common_v3_10_a/hdl/src/vhdl/system_xadc_0_pselect_f.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_address_decoder.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_slave_attachment.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/interrupt_control_v2_01_a/hdl/src/vhdl/system_xadc_0_interrupt_control.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_axi_lite_ipif.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_xadc_core_drp.vhd
      /home/jiu/ma/jiu3/lock_in_48/fpga/.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_axi_xadc.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-33709-jiu-730QCJ-730QCR/realtime/red_pitaya_top_synth.xdc
    rt::sdcChecksum
    set rt::top red_pitaya_top
    set rt::flattenHierarchy 3
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter maxClockBufferCount 16
    rt::set_parameter repFanoutThreshold 100
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops false
    rt::set_parameter webTalkPath {./.Xil/Vivado-33709-jiu-730QCJ-730QCR/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-33709-jiu-730QCJ-730QCR/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
